// auto generated by rpc-ts-gen don't break
/* tslint-disable */
/* eslint-disable */

export  enum ErrorCode { 
    
  Success = "Success", 
  
  InvalidParameter = "InvalidParameter", 
  
  TopicNotExist = "TopicNotExist", 
  
  GroupNotExist = "GroupNotExist", 
  
  UnsurpportedClientType = "UnsurpportedClientType", 
  
  NoAccessPermissionForTopic = "NoAccessPermissionForTopic", 
  
  NoAccessPermissionForGroup = "NoAccessPermissionForGroup", 
  
  InvalidProperties = "InvalidProperties", 
  
  ClientNotFound = "ClientNotFound", 
  
  ReqBodyNotExist = "ReqBodyNotExist", 
  
  InternalServerError = "InternalServerError", 
  
  ClientHasTaskRunning = "ClientHasTaskRunning", 
  
  ReqBodyTooLarge = "ReqBodyTooLarge", 
  
  AckMessageError = "AckMessageError", 
  
  UnknownError = "UnknownError", 
  
  InvalidPollRequestParam = "InvalidPollRequestParam", 
  
  ProducerGroupHasAlreadyExist = "ProducerGroupHasAlreadyExist", 
  
  InvalidDelayTimeLevel = "InvalidDelayTimeLevel", 
  
  RetryErrorCodeStart = "RetryErrorCodeStart", 
  
  TooManyWaitAckMessage = "TooManyWaitAckMessage", 
  
  TooManyOpenRequest = "TooManyOpenRequest", 
  
  TooManyAckRequest = "TooManyAckRequest", 
  
  TooManySendRequest = "TooManySendRequest" 
}

export interface ErrorDetail {
  HttpErrCode: number;
  /** 描述 */
  Description: string;
}
